//----------------------------------------------------------------------------
//
//  Copyright (C) 2004-2022 by EMGU Corporation. All rights reserved.
//
//  Vector of VectorOfPointF
//
//  This file is automatically generated, do not modify.
//----------------------------------------------------------------------------



#include "vector_VectorOfPointF.h"

#if 1



std::vector< std::vector< cv::Point2f > >* VectorOfVectorOfPointFCreate() 
{
   return new std::vector< std::vector< cv::Point2f > >(); 
}

std::vector< std::vector< cv::Point2f > >* VectorOfVectorOfPointFCreateSize(int size) 
{
   return new std::vector< std::vector< cv::Point2f > >(size); 
}

int VectorOfVectorOfPointFGetSize(std::vector< std::vector< cv::Point2f > >* v)
{
   return v->size();
}


void VectorOfVectorOfPointFPush(std::vector< std::vector< cv::Point2f > >* v, std::vector< cv::Point2f >* value)
{
   v->push_back(*value);
}

//void VectorOfVectorOfPointFPushMulti(std::vector< std::vector< cv::Point2f > >* v,  std::vector< cv::Point2f >* values, int count)
//{
//   VectorPushMulti< std::vector< cv::Point2f > >(v, values, count);
//}

void VectorOfVectorOfPointFPushVector(std::vector< std::vector< cv::Point2f > >* v, std::vector< std::vector< cv::Point2f > >* other)
{
   v->insert(v->end(), other->begin(), other->end());
}

void VectorOfVectorOfPointFClear(std::vector< std::vector< cv::Point2f > >* v)
{
   v->clear();
}

void VectorOfVectorOfPointFRelease(std::vector< std::vector< cv::Point2f > >** v)
{
   delete *v;
   *v = 0;
}

void VectorOfVectorOfPointFCopyData(std::vector< std::vector< cv::Point2f > >* v, std::vector< cv::Point2f >* data)
{
   VectorCopyData< std::vector< cv::Point2f > >(v, data);
}

std::vector< cv::Point2f >* VectorOfVectorOfPointFGetStartAddress(std::vector< std::vector< cv::Point2f > >* v)
{
   return v->empty() ? NULL : &(*v)[0];
}

int64_t VectorOfVectorOfPointFGetMemorySize(std::vector< std::vector< cv::Point2f > >* v)
{
   if (v->empty()) return 0;
   return (int64_t) (v->size() * sizeof(std::vector< cv::Point2f >));
}

void VectorOfVectorOfPointFGetItemPtr(std::vector<  std::vector< cv::Point2f > >* vec, int index,  std::vector< cv::Point2f >** element)
{
   *element = &vec->at(index);
}

#if true
cv::_InputArray* cveInputArrayFromVectorOfVectorOfPointF(std::vector< std::vector< cv::Point2f > >* vec)
{
   return new cv::_InputArray(*vec);
}

cv::_OutputArray* cveOutputArrayFromVectorOfVectorOfPointF(std::vector< std::vector< cv::Point2f > >* vec)
{
   return new cv::_OutputArray(*vec);
}

cv::_InputOutputArray* cveInputOutputArrayFromVectorOfVectorOfPointF(std::vector< std::vector< cv::Point2f > >* vec)
{
   return new cv::_InputOutputArray(*vec);
}
#endif

int VectorOfVectorOfPointFSizeOfItemInBytes()
{
   return sizeof(std::vector< cv::Point2f >);
}

#else

void * VectorOfVectorOfPointFCreate()
{
   throw_no_vector();
}

void * VectorOfVectorOfPointFCreateSize(int size)
{
   throw_no_vector();
}

int VectorOfVectorOfPointFGetSize(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfPointFPush(void* v, void* value)
{
   throw_no_vector();
}

//CVAPI(void) VectorOfVectorOfPointFPushMulti(std::vector< std::vector< cv::Point2f > >* v, std::vector< cv::Point2f >* values, int count);

void VectorOfVectorOfPointFPushVector(void* v, void* other)
{
   throw_no_vector();
}

void VectorOfVectorOfPointFClear(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfPointFRelease(void** v)
{
   throw_no_vector();
}

void VectorOfVectorOfPointFCopyData(void* v, void* data)
{
   throw_no_vector();
}

void* VectorOfVectorOfPointFGetStartAddress(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfPointFGetItemPtr(void* vec, int index,  void** element)
{
   throw_no_vector();
}

#if true
cv::_InputArray* cveInputArrayFromVectorOfVectorOfPointF(void* vec)
{
   throw_no_vector();
}

cv::_OutputArray* cveOutputArrayFromVectorOfVectorOfPointF(void* vec)
{
   throw_no_vector();
}

cv::_InputOutputArray* cveInputOutputArrayFromVectorOfVectorOfPointF(void* vec)
{
   throw_no_vector();
}
#endif

int VectorOfVectorOfPointFSizeOfItemInBytes()
{
   throw_no_vector();
}


#endif
