//----------------------------------------------------------------------------
//
//  Copyright (C) 2004-2022 by EMGU Corporation. All rights reserved.
//
//  Vector of VectorOfByte
//
//  This file is automatically generated, do not modify.
//----------------------------------------------------------------------------



#include "vector_VectorOfByte.h"

#if 1



std::vector< std::vector< unsigned char > >* VectorOfVectorOfByteCreate() 
{
   return new std::vector< std::vector< unsigned char > >(); 
}

std::vector< std::vector< unsigned char > >* VectorOfVectorOfByteCreateSize(int size) 
{
   return new std::vector< std::vector< unsigned char > >(size); 
}

int VectorOfVectorOfByteGetSize(std::vector< std::vector< unsigned char > >* v)
{
   return v->size();
}


void VectorOfVectorOfBytePush(std::vector< std::vector< unsigned char > >* v, std::vector< unsigned char >* value)
{
   v->push_back(*value);
}

//void VectorOfVectorOfBytePushMulti(std::vector< std::vector< unsigned char > >* v,  std::vector< unsigned char >* values, int count)
//{
//   VectorPushMulti< std::vector< unsigned char > >(v, values, count);
//}

void VectorOfVectorOfBytePushVector(std::vector< std::vector< unsigned char > >* v, std::vector< std::vector< unsigned char > >* other)
{
   v->insert(v->end(), other->begin(), other->end());
}

void VectorOfVectorOfByteClear(std::vector< std::vector< unsigned char > >* v)
{
   v->clear();
}

void VectorOfVectorOfByteRelease(std::vector< std::vector< unsigned char > >** v)
{
   delete *v;
   *v = 0;
}

void VectorOfVectorOfByteCopyData(std::vector< std::vector< unsigned char > >* v, std::vector< unsigned char >* data)
{
   VectorCopyData< std::vector< unsigned char > >(v, data);
}

std::vector< unsigned char >* VectorOfVectorOfByteGetStartAddress(std::vector< std::vector< unsigned char > >* v)
{
   return v->empty() ? NULL : &(*v)[0];
}

int64_t VectorOfVectorOfByteGetMemorySize(std::vector< std::vector< unsigned char > >* v)
{
   if (v->empty()) return 0;
   return (int64_t) (v->size() * sizeof(std::vector< unsigned char >));
}

void VectorOfVectorOfByteGetItemPtr(std::vector<  std::vector< unsigned char > >* vec, int index,  std::vector< unsigned char >** element)
{
   *element = &vec->at(index);
}

#if true
cv::_InputArray* cveInputArrayFromVectorOfVectorOfByte(std::vector< std::vector< unsigned char > >* vec)
{
   return new cv::_InputArray(*vec);
}

cv::_OutputArray* cveOutputArrayFromVectorOfVectorOfByte(std::vector< std::vector< unsigned char > >* vec)
{
   return new cv::_OutputArray(*vec);
}

cv::_InputOutputArray* cveInputOutputArrayFromVectorOfVectorOfByte(std::vector< std::vector< unsigned char > >* vec)
{
   return new cv::_InputOutputArray(*vec);
}
#endif

int VectorOfVectorOfByteSizeOfItemInBytes()
{
   return sizeof(std::vector< unsigned char >);
}

#else

void * VectorOfVectorOfByteCreate()
{
   throw_no_vector();
}

void * VectorOfVectorOfByteCreateSize(int size)
{
   throw_no_vector();
}

int VectorOfVectorOfByteGetSize(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfBytePush(void* v, void* value)
{
   throw_no_vector();
}

//CVAPI(void) VectorOfVectorOfBytePushMulti(std::vector< std::vector< unsigned char > >* v, std::vector< unsigned char >* values, int count);

void VectorOfVectorOfBytePushVector(void* v, void* other)
{
   throw_no_vector();
}

void VectorOfVectorOfByteClear(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfByteRelease(void** v)
{
   throw_no_vector();
}

void VectorOfVectorOfByteCopyData(void* v, void* data)
{
   throw_no_vector();
}

void* VectorOfVectorOfByteGetStartAddress(void* v)
{
   throw_no_vector();
}

void VectorOfVectorOfByteGetItemPtr(void* vec, int index,  void** element)
{
   throw_no_vector();
}

#if true
cv::_InputArray* cveInputArrayFromVectorOfVectorOfByte(void* vec)
{
   throw_no_vector();
}

cv::_OutputArray* cveOutputArrayFromVectorOfVectorOfByte(void* vec)
{
   throw_no_vector();
}

cv::_InputOutputArray* cveInputOutputArrayFromVectorOfVectorOfByte(void* vec)
{
   throw_no_vector();
}
#endif

int VectorOfVectorOfByteSizeOfItemInBytes()
{
   throw_no_vector();
}


#endif
